[[roots]]
dir = "/path/to/parent1/dir/"

[[roots.children]]
hostname = "hostname1"
dir = "/path/to/hostname1/dir/"

[[roots.children]]
hostname = "hostname2"
dir = "/path/to/hostname2/dir/"

[[roots]]
dir = "/path/to/parent2/dir/"

[[roots.children]]
hostname = "hostname1"
dir = "/path/to/hostname1/dir/"
